apiVersion: v1
kind: Pod
metadata:
  name: upsource
  labels:
    name: upsource
spec:
  containers:
    - image: gcr.io/droidcon-backend/upsource:latest
      name: upsource
      ports:
        - name: http
          hostPort: 8080
          containerPort: 80
      volumeMounts:
          # Name must match the volume name below.
        - name: upsource-disk
          # Mount path within the container.
          mountPath: /var/upsource
  volumes:
    - name: upsource-disk
      gcePersistentDisk:
        # This GCE persistent disk must already exist.
        pdName: upsource-disk
        fsType: ext4